apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-deployment-template
  title: Terraform Deployment Template
  description: Template for deploying Terraform code from a separate repository
  tags:
    - terraform
    - iac
    - recommended
spec:
  owner: development
  type: service

  parameters:
    - title: Provide deployment information
      required:
        - component_id
        - owner
        - terraform_repo_url
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name for the deployment
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this deployment does
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        terraform_repo_url:
          title: Terraform Repository URL
          type: string
          description: URL to the Git repository containing Terraform code
        terraform_directory:
          title: Terraform Directory
          type: string
          description: Path to Terraform code within the repository
          default: "/"

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          terraform_repo_url: ${{ parameters.terraform_repo_url }}
          terraform_directory: ${{ parameters.terraform_directory }}
          terraform_version: ${{ parameters.terraform_version }}
          tf_vars: ${{ parameters.tf_vars }}
          environment: ${{ parameters.environment }}
          auto_apply: ${{ parameters.auto_apply }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=VinodKumarKP1984&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}